# Generated by Django 3.1.4 on 2020-12-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weburl',
            name='page',
        ),
    ]
